pipeline{
    agent any
    environment{
        DATABASE_URI = credentials("DATABASE_URI")
        app_version = 'v1'
        rollback = 'false'
        replicas = 3
    }
    stages{
        stage("Testing"){
            steps{
                script{
                    if (env.rollback == 'false') {
                        sh "bash qa-project2/jenkins/test.sh"
                    }
                }
            }
        }
        stage("Build & Push"){
            steps{
                script{
                    if (env.rollback == 'false') {
                        sh "cd qa-project2 && docker-compose build --parallel && docker-compose push"
                        sh "docker system prune -af"
                    }
                }
            }
        }
        stage("Config Management (ansible)"){
            steps{
                sh "cd qa-project2/ansible && /home/jenkins/.local/bin/ansible-playbook -i inventory playbook.yaml"
            }
        }
        stage("Deploy"){
            steps{
                sh "bash qa-project2/jenkins/deploy.sh"
            }
        }
    }
    post{
        always{
            junit "**/junit.xml"
            cobertura coberturaReportFile: '**/coverage.xml', failNoReports: false, failUnstable: false, onlyStable: false
        }
    }
}