version: '3.8'
services:
  qrandom:
    container_name: qrandom_qrandom
    image: gregkomu/qrandom_qrandom
    build: ./serv-1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
  qrandom-qran:
    container_name: qrandom_qrandom-qran
    build: ./serv-2
    image: gregkomu/qrandom_qrandom-qran
  qrandom-meal:
    container_name: qrandom_qrandom-meal
    build: ./serv-3
    image: gregkomu/qrandom_qrandom-meal
  qrandom-whatudone:
    container_name: qrandom_qrandom-whatudone
    build: ./serv-4
    image: gregkomu/qrandom_qrandom-whatudone