version: '3.8'
services:
  qrandom:
    container_name: qrandom_qrandom
    image: gregkomu/qrandom_qrandom:basic
    build: ./serv-1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      
    deploy:
      replicas: 3
  qrandom-qran:
    container_name: qrandom_qrandom-qran
    build: ./serv-2
    image: gregkomu/qrandom_qrandom-qran:basic
    deploy:
      replicas: 3
  qrandom-meal:
    container_name: qrandom_qrandom-meal
    build: ./serv-3
    image: gregkomu/qrandom_qrandom-meal:basic
    deploy:
      replicas: 3
  qrandom-whatudone:
    container_name: qrandom_qrandom-whatudone
    build: ./serv-4
    image: gregkomu/qrandom_qrandom-whatudone:basic
    deploy:
      replicas: 3