version: '3.8'
services:
  qrandom:

    container_name: qrandom_qrandom-v
    image: gregkomu/qrandom_qrandom_vegan

    build: ./serv-1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI}
      
    deploy:
      replicas: 3
  qrandom-qran:
    container_name: qrandom_qrandom-qran-v
    build: ./serv-2

    image: gregkomu/qrandom_qrandom-qran_vegan
   
    deploy:
      replicas: 3
  qrandom-meal:
    container_name: qrandom_qrandom-meal-v
    build: ./serv-3

    image: gregkomu/qrandom_qrandom-meal_vegan

    
    deploy:
      replicas: 3
  qrandom-whatudone:
    container_name: qrandom_qrandom-whatudone-v
    build: ./serv-4

    image: gregkomu/qrandom_qrandom-whatudone_vegan

    deploy:
      replicas: 3